In [1]:
#!/usr/bin/env python
# -*- coding: utf-8 -*-
import cv2
import numpy as np
import tensorflow as tf
from tensorflow.keras.preprocessing import image

face_cascade = cv2.CascadeClassifier(cv2.data.haarcascades+"haarcascade_frontalface_default.xml")
cam = cv2.VideoCapture(0)

keras_model_path = './callbacks_CK/emtion_model_CK.h5'
emotion_labels = ['anger', 'disgust', 'Surprised',
                'happy', 'sad','natural','afriad' ]
font = cv2.FONT_HERSHEY_SIMPLEX

In [2]:
restored_keras_model = tf.keras.models.load_model(keras_model_path)
print(restored_keras_model.metrics_names)

['loss', 'accuracy']


In [3]:
def EmtionDetect (img):
    face_area = img[y-h//4:y+h+h//4, x-w//4:x+w+w//4]
    face_area_gray = cv2.cvtColor(face_area, cv2.COLOR_BGR2GRAY)
    face_area_gray = cv2.cvtColor(face_area_gray, cv2.COLOR_GRAY2BGR)
    face_area_gray = cv2.resize(face_area_gray,(48, 48))
    face_area_gray = face_area_gray/255
    array_img = image.img_to_array(face_area_gray)
    array_img = np.expand_dims(array_img, axis=0)
    emotion_prediction = restored_keras_model(array_img)
    print(emotion_prediction)
    emotionprobability = np.max(emotion_prediction)
    emotion_label_arg = np.argmax(emotion_prediction)
    emotion_text = emotion_labels[emotion_label_arg]  
    return emotion_text

In [4]:
while(True):
    ret, frame = cam.read()
    faces = face_cascade.detectMultiScale(frame, 1.3, 5)
    img = frame
    for (x,y,w,h) in faces:
        img = cv2.rectangle(img,(x,y),(x+w,y+h),(255,0,0),2)
        predict_result = EmtionDetect(img)
        cv2.putText(img=frame, text=predict_result, org=(x, y), fontFace=font, color=(255,255,255), fontScale = 2)
    cv2.imshow('frame',img)
    if cv2.waitKey(5) & 0xFF == ord('q'):
        break

cam.release()
cv2.destroyAllWindows()

tf.Tensor(
[[2.6739573e-01 6.2385425e-03 1.3833890e-02 3.0395063e-04 2.9394823e-06
  3.8878533e-01 3.2343966e-01]], shape=(1, 7), dtype=float32)
tf.Tensor(
[[3.0289334e-01 4.9452656e-03 1.4790782e-02 2.2478073e-04 1.6283146e-06
  4.3215522e-01 2.4498904e-01]], shape=(1, 7), dtype=float32)
tf.Tensor(
[[3.0255577e-01 4.9663926e-03 1.5066080e-02 2.2114278e-04 1.6076369e-06
  4.4488239e-01 2.3230666e-01]], shape=(1, 7), dtype=float32)
tf.Tensor(
[[1.9666871e-01 4.4997935e-03 9.1433367e-03 2.0461780e-04 1.5470259e-06
  4.1942370e-01 3.7005824e-01]], shape=(1, 7), dtype=float32)
tf.Tensor(
[[1.9666871e-01 4.4997935e-03 9.1433367e-03 2.0461780e-04 1.5470259e-06
  4.1942370e-01 3.7005824e-01]], shape=(1, 7), dtype=float32)
tf.Tensor(
[[1.7470042e-01 5.1974454e-03 8.9311441e-03 2.4814074e-04 2.1262872e-06
  3.8992479e-01 4.2099592e-01]], shape=(1, 7), dtype=float32)
tf.Tensor(
[[2.1135631e-01 6.0528717e-03 1.0235364e-02 2.8397632e-04 2.6420701e-06
  3.9884773e-01 3.7322113e-01]], shape=(1, 7), 

tf.Tensor(
[[9.1526783e-01 3.2345805e-02 2.5408554e-03 1.9770702e-02 2.9195589e-04
  2.6211960e-02 3.5709389e-03]], shape=(1, 7), dtype=float32)
tf.Tensor(
[[9.1526783e-01 3.2345805e-02 2.5408554e-03 1.9770702e-02 2.9195589e-04
  2.6211960e-02 3.5709389e-03]], shape=(1, 7), dtype=float32)
tf.Tensor(
[[9.0781033e-01 3.6409609e-02 3.6420792e-03 2.1770779e-02 4.2689042e-04
  2.6215868e-02 3.7243492e-03]], shape=(1, 7), dtype=float32)
tf.Tensor(
[[9.0781033e-01 3.6409609e-02 3.6420792e-03 2.1770779e-02 4.2689042e-04
  2.6215868e-02 3.7243492e-03]], shape=(1, 7), dtype=float32)
tf.Tensor(
[[9.2923576e-01 2.7816754e-02 3.0662073e-03 1.1305299e-02 2.2860536e-04
  2.5974378e-02 2.3729044e-03]], shape=(1, 7), dtype=float32)
tf.Tensor(
[[9.2867523e-01 3.0455472e-02 2.3949123e-03 1.4577773e-02 2.4137439e-04
  2.1762898e-02 1.8924576e-03]], shape=(1, 7), dtype=float32)
tf.Tensor(
[[9.2867523e-01 3.0455472e-02 2.3949123e-03 1.4577773e-02 2.4137439e-04
  2.1762898e-02 1.8924576e-03]], shape=(1, 7), 

tf.Tensor(
[[0.7656347  0.12088607 0.00141222 0.07567704 0.00149453 0.01607481
  0.01882062]], shape=(1, 7), dtype=float32)
tf.Tensor(
[[0.7656347  0.12088607 0.00141222 0.07567704 0.00149453 0.01607481
  0.01882062]], shape=(1, 7), dtype=float32)
tf.Tensor(
[[0.6852787  0.16703098 0.0010478  0.10438112 0.00123955 0.0193469
  0.02167489]], shape=(1, 7), dtype=float32)
tf.Tensor(
[[0.64447415 0.20604691 0.00080254 0.10548411 0.000995   0.01986066
  0.02233668]], shape=(1, 7), dtype=float32)
tf.Tensor(
[[0.64447415 0.20604691 0.00080254 0.10548411 0.000995   0.01986066
  0.02233668]], shape=(1, 7), dtype=float32)
tf.Tensor(
[[0.6442602  0.19665566 0.0011529  0.11078353 0.00185105 0.01645039
  0.02884625]], shape=(1, 7), dtype=float32)
tf.Tensor(
[[0.6442602  0.19665566 0.0011529  0.11078353 0.00185105 0.01645039
  0.02884625]], shape=(1, 7), dtype=float32)
tf.Tensor(
[[0.77312136 0.12094105 0.00186262 0.0701699  0.00230845 0.01248683
  0.01910983]], shape=(1, 7), dtype=float32)
tf.Tensor

tf.Tensor(
[[8.7860686e-01 8.2781821e-02 2.4455837e-03 6.2551554e-03 2.1444267e-04
  1.5811786e-02 1.3884262e-02]], shape=(1, 7), dtype=float32)
tf.Tensor(
[[8.5737485e-01 8.7210760e-02 1.9664923e-03 7.5304848e-03 1.3147159e-04
  3.3224363e-02 1.2561640e-02]], shape=(1, 7), dtype=float32)
tf.Tensor(
[[8.5737485e-01 8.7210760e-02 1.9664923e-03 7.5304848e-03 1.3147159e-04
  3.3224363e-02 1.2561640e-02]], shape=(1, 7), dtype=float32)
tf.Tensor(
[[0.8084578  0.14593329 0.00532646 0.01928444 0.00160109 0.01604192
  0.00335492]], shape=(1, 7), dtype=float32)
tf.Tensor(
[[0.7621563  0.17570567 0.00768012 0.0375635  0.00503345 0.00971158
  0.00214937]], shape=(1, 7), dtype=float32)
tf.Tensor(
[[0.7621563  0.17570567 0.00768012 0.0375635  0.00503345 0.00971158
  0.00214937]], shape=(1, 7), dtype=float32)
tf.Tensor(
[[0.6579346  0.24774015 0.00555184 0.06817669 0.00606687 0.01222391
  0.00230588]], shape=(1, 7), dtype=float32)
tf.Tensor(
[[0.8704202  0.08495175 0.00737195 0.02496099 0.00330804 0

tf.Tensor(
[[8.79860699e-01 7.69870654e-02 1.28081918e-03 9.81894415e-03
  1.41531200e-04 1.40796695e-02 1.78312957e-02]], shape=(1, 7), dtype=float32)
tf.Tensor(
[[8.79860699e-01 7.69870654e-02 1.28081918e-03 9.81894415e-03
  1.41531200e-04 1.40796695e-02 1.78312957e-02]], shape=(1, 7), dtype=float32)
tf.Tensor(
[[9.5323455e-01 2.8542943e-02 3.1837770e-03 4.1365395e-03 1.7629442e-04
  8.2684755e-03 2.4574629e-03]], shape=(1, 7), dtype=float32)
tf.Tensor(
[[9.2000669e-01 4.9564395e-02 2.0594783e-03 9.2528341e-03 2.8294936e-04
  8.6177159e-03 1.0216087e-02]], shape=(1, 7), dtype=float32)
tf.Tensor(
[[9.2000669e-01 4.9564395e-02 2.0594783e-03 9.2528341e-03 2.8294936e-04
  8.6177159e-03 1.0216087e-02]], shape=(1, 7), dtype=float32)
tf.Tensor(
[[9.5136762e-01 2.9289396e-02 2.6848211e-03 4.0629283e-03 1.3611150e-04
  1.0142904e-02 2.3162444e-03]], shape=(1, 7), dtype=float32)
tf.Tensor(
[[9.5136762e-01 2.9289396e-02 2.6848211e-03 4.0629283e-03 1.3611150e-04
  1.0142904e-02 2.3162444e-03]], 

tf.Tensor(
[[0.05850824 0.09064236 0.00229874 0.49723548 0.00133218 0.3323788
  0.01760422]], shape=(1, 7), dtype=float32)
tf.Tensor(
[[0.11445634 0.26106438 0.00630824 0.42923108 0.00735053 0.16105448
  0.02053498]], shape=(1, 7), dtype=float32)
tf.Tensor(
[[0.11445634 0.26106438 0.00630824 0.42923108 0.00735053 0.16105448
  0.02053498]], shape=(1, 7), dtype=float32)
tf.Tensor(
[[0.15193324 0.26573485 0.01104576 0.40268394 0.01061131 0.14057171
  0.01741915]], shape=(1, 7), dtype=float32)
tf.Tensor(
[[0.13096026 0.24875063 0.01065945 0.44325304 0.01096004 0.13037196
  0.02504457]], shape=(1, 7), dtype=float32)
tf.Tensor(
[[0.13096026 0.24875063 0.01065945 0.44325304 0.01096004 0.13037196
  0.02504457]], shape=(1, 7), dtype=float32)
tf.Tensor(
[[0.1018558  0.1943851  0.00627201 0.4626542  0.00510144 0.20847824
  0.02125322]], shape=(1, 7), dtype=float32)
tf.Tensor(
[[0.14203839 0.33994275 0.01137077 0.4003082  0.01763616 0.07613394
  0.01256972]], shape=(1, 7), dtype=float32)
tf.Tensor

tf.Tensor(
[[0.05051902 0.10373004 0.00160172 0.43661526 0.00113443 0.35321748
  0.05318198]], shape=(1, 7), dtype=float32)
tf.Tensor(
[[0.05051902 0.10373004 0.00160172 0.43661526 0.00113443 0.35321748
  0.05318198]], shape=(1, 7), dtype=float32)
tf.Tensor(
[[0.10005646 0.23963115 0.00451981 0.34808096 0.0041314  0.23064889
  0.07293128]], shape=(1, 7), dtype=float32)
tf.Tensor(
[[0.09105083 0.24920315 0.00385823 0.3648551  0.00415927 0.22506334
  0.06181011]], shape=(1, 7), dtype=float32)
tf.Tensor(
[[0.07671624 0.2103023  0.00538832 0.43325746 0.00634288 0.19990842
  0.06808446]], shape=(1, 7), dtype=float32)
tf.Tensor(
[[0.07671624 0.2103023  0.00538832 0.43325746 0.00634288 0.19990842
  0.06808446]], shape=(1, 7), dtype=float32)
tf.Tensor(
[[0.09854065 0.23795946 0.00352551 0.35931405 0.00341862 0.25190496
  0.04533673]], shape=(1, 7), dtype=float32)
tf.Tensor(
[[0.09854065 0.23795946 0.00352551 0.35931405 0.00341862 0.25190496
  0.04533673]], shape=(1, 7), dtype=float32)
tf.Tenso

tf.Tensor(
[[8.1986421e-01 8.9370452e-02 1.1323683e-03 5.0702184e-02 3.7906680e-04
  3.1784106e-02 6.7675607e-03]], shape=(1, 7), dtype=float32)
tf.Tensor(
[[8.1986421e-01 8.9370452e-02 1.1323683e-03 5.0702184e-02 3.7906680e-04
  3.1784106e-02 6.7675607e-03]], shape=(1, 7), dtype=float32)
tf.Tensor(
[[8.1374860e-01 8.3370298e-02 9.7781781e-04 5.5780772e-02 3.0574761e-04
  3.8081184e-02 7.7354778e-03]], shape=(1, 7), dtype=float32)
tf.Tensor(
[[8.4138942e-01 7.6221354e-02 2.0824079e-03 3.6635689e-02 3.7537538e-04
  3.6686994e-02 6.6088508e-03]], shape=(1, 7), dtype=float32)
tf.Tensor(
[[8.4138942e-01 7.6221354e-02 2.0824079e-03 3.6635689e-02 3.7537538e-04
  3.6686994e-02 6.6088508e-03]], shape=(1, 7), dtype=float32)
tf.Tensor(
[[7.8640556e-01 8.8021517e-02 8.6884800e-04 6.2726960e-02 2.1849014e-04
  5.1797517e-02 9.9610500e-03]], shape=(1, 7), dtype=float32)
tf.Tensor(
[[8.2322717e-01 8.4957831e-02 1.0720253e-03 4.6923339e-02 3.1695658e-04
  3.6312576e-02 7.1901479e-03]], shape=(1, 7), 

tf.Tensor(
[[8.6632717e-01 6.6979393e-02 2.5063569e-03 2.2446806e-02 3.1292959e-04
  3.8878497e-02 2.5489409e-03]], shape=(1, 7), dtype=float32)
tf.Tensor(
[[8.7351108e-01 6.0245052e-02 2.6352892e-03 2.1113170e-02 2.6969280e-04
  4.0040907e-02 2.1846942e-03]], shape=(1, 7), dtype=float32)
tf.Tensor(
[[8.7664968e-01 6.4638197e-02 3.0145324e-03 1.8927503e-02 3.2967934e-04
  3.4722712e-02 1.7175894e-03]], shape=(1, 7), dtype=float32)
tf.Tensor(
[[8.7664968e-01 6.4638197e-02 3.0145324e-03 1.8927503e-02 3.2967934e-04
  3.4722712e-02 1.7175894e-03]], shape=(1, 7), dtype=float32)
tf.Tensor(
[[9.08686340e-01 4.26451340e-02 2.14851904e-03 1.19951395e-02
  1.54055888e-04 3.18812840e-02 2.48952140e-03]], shape=(1, 7), dtype=float32)
tf.Tensor(
[[8.7956440e-01 6.4413548e-02 4.7641736e-03 1.7358968e-02 4.7036581e-04
  3.1932011e-02 1.4965083e-03]], shape=(1, 7), dtype=float32)
tf.Tensor(
[[8.8836467e-01 5.9424587e-02 3.8564277e-03 1.6894422e-02 3.8378502e-04
  2.9731214e-02 1.3448072e-03]], shape=(

tf.Tensor(
[[9.1652089e-01 5.5279475e-02 3.2673494e-03 1.1250425e-02 5.7631929e-04
  9.3952026e-03 3.7103610e-03]], shape=(1, 7), dtype=float32)
tf.Tensor(
[[9.1652089e-01 5.5279475e-02 3.2673494e-03 1.1250425e-02 5.7631929e-04
  9.3952026e-03 3.7103610e-03]], shape=(1, 7), dtype=float32)
tf.Tensor(
[[0.7461051  0.16021124 0.00176098 0.05353767 0.0012267  0.01841943
  0.01873889]], shape=(1, 7), dtype=float32)
tf.Tensor(
[[0.88265526 0.07060886 0.00275325 0.02582598 0.00118369 0.01098419
  0.00598872]], shape=(1, 7), dtype=float32)
tf.Tensor(
[[0.88265526 0.07060886 0.00275325 0.02582598 0.00118369 0.01098419
  0.00598872]], shape=(1, 7), dtype=float32)
tf.Tensor(
[[0.81918687 0.10605121 0.00318241 0.04592507 0.00232495 0.01459204
  0.00873741]], shape=(1, 7), dtype=float32)
tf.Tensor(
[[0.6517183  0.20400776 0.00156224 0.07447763 0.00197717 0.01651181
  0.04974509]], shape=(1, 7), dtype=float32)
tf.Tensor(
[[0.6077114  0.21336032 0.00157585 0.0894821  0.00223318 0.01959682
  0.0660403

tf.Tensor(
[[8.8693404e-01 8.7073192e-02 1.7008113e-03 9.1460450e-03 4.4187417e-04
  6.0643405e-03 8.6397966e-03]], shape=(1, 7), dtype=float32)
tf.Tensor(
[[9.3169641e-01 4.9503841e-02 2.2823811e-03 7.6627592e-03 3.6761587e-04
  5.9591415e-03 2.5277256e-03]], shape=(1, 7), dtype=float32)
tf.Tensor(
[[9.3169641e-01 4.9503841e-02 2.2823811e-03 7.6627592e-03 3.6761587e-04
  5.9591415e-03 2.5277256e-03]], shape=(1, 7), dtype=float32)
tf.Tensor(
[[9.3774563e-01 4.3941803e-02 1.9771548e-03 7.5502796e-03 3.0889656e-04
  6.2038205e-03 2.2723989e-03]], shape=(1, 7), dtype=float32)
tf.Tensor(
[[9.2033434e-01 5.9149496e-02 1.8898842e-03 9.4617568e-03 4.0781207e-04
  5.9904973e-03 2.7662530e-03]], shape=(1, 7), dtype=float32)
tf.Tensor(
[[9.2033434e-01 5.9149496e-02 1.8898842e-03 9.4617568e-03 4.0781207e-04
  5.9904973e-03 2.7662530e-03]], shape=(1, 7), dtype=float32)
tf.Tensor(
[[9.3424320e-01 4.7358889e-02 2.1375220e-03 7.5812852e-03 3.5573929e-04
  5.8794389e-03 2.4438987e-03]], shape=(1, 7), 

tf.Tensor(
[[6.7286938e-01 3.8837139e-02 5.4175374e-03 4.6796338e-03 7.6579694e-05
  4.2990159e-02 2.3512957e-01]], shape=(1, 7), dtype=float32)
tf.Tensor(
[[3.28545511e-01 1.13981515e-02 1.05136335e-02 2.16827588e-03
  1.30976605e-05 1.58682451e-01 4.88678843e-01]], shape=(1, 7), dtype=float32)
tf.Tensor(
[[3.28545511e-01 1.13981515e-02 1.05136335e-02 2.16827588e-03
  1.30976605e-05 1.58682451e-01 4.88678843e-01]], shape=(1, 7), dtype=float32)
tf.Tensor(
[[1.4776847e-01 5.8266958e-03 5.9883464e-03 1.4402993e-03 5.1124021e-06
  2.2984326e-01 6.0912788e-01]], shape=(1, 7), dtype=float32)
tf.Tensor(
[[2.2159579e-01 8.0354540e-03 8.1687989e-03 1.6516817e-03 8.4022467e-06
  1.9699480e-01 5.6354505e-01]], shape=(1, 7), dtype=float32)
tf.Tensor(
[[2.2159579e-01 8.0354540e-03 8.1687989e-03 1.6516817e-03 8.4022467e-06
  1.9699480e-01 5.6354505e-01]], shape=(1, 7), dtype=float32)
tf.Tensor(
[[3.45729798e-01 1.48930345e-02 1.99197903e-02 3.42252408e-03
  3.59512014e-05 3.08867007e-01 3.07131946e